Luos-io/Documentation

.github/workflows/build.yml, .github/workflows/check.yml
Add some automatic check for Documentation : 
Check link will fail for now because doc is not complete yet.
=> add documentation checkup to github

src/index.md
=> Index page

src/_pages/prototyping_boards/electronic-use.md
Fill the last section at the end of file electronic-use.md
=> Add section update board's firmware

src/_pages/prototyping_boards/boards_list/battery-power-input.md, src/_pages/prototyping_boards/boards_list/button.md, src/_pages/prototyping_boards/boards_list/cables.md, src/_pages/prototyping_boards/boards_list/controlled-motor.md, src/_pages/prototyping_boards/boards_list/dc-motor.md, src/_pages/prototyping_boards/boards_list/distance.md, src/_pages/prototyping_boards/boards_list/dxl.md, src/_pages/prototyping_boards/boards_list/gpio.md, src/_pages/prototyping_boards/boards_list/imu.md, src/_pages/prototyping_boards/boards_list/jack-power-input.md, src/_pages/prototyping_boards/boards_list/light.md, src/_pages/prototyping_boards/boards_list/potentiometer.md, src/_pages/prototyping_boards/boards_list/power-isolator.md, src/_pages/prototyping_boards/boards_list/powerpi.md, src/_pages/prototyping_boards/boards_list/powerswitch.md, src/_pages/prototyping_boards/boards_list/rgbled.md, src/_pages/prototyping_boards/boards_list/servo.md, src/_pages/prototyping_boards/boards_list/stepper.md, src/_pages/prototyping_boards/boards_list/usb.md, src/_pages/prototyping_boards/boards_list/wifible.md
Add links to GH pages for every module
=> Add link to modules in prototyping boards fix #47

src/pages/high/json-api.md, src/pages/high/pyluos.md
Add information on how to get the version of Luos and Robus from Pyluos in the documentation (chapter JSON-API and Pyluos).
=> Pyluos luos robus version

src/pages/high/json-api.md, src/pages/low/dev-env.md, src/theme/index.hbs
- Add parameters info
- Regroup parameters in a table with links to structures
- Regroup other objects in a table
=> Parameters

src/pages/high/pyluos.md, src/pages/low/containers/create-project.md, src/pages/low/containers/msg-handling.md, src/pages/low/containers/routing-table.md, src/pages/low/dev-env.md, src/pages/low/electronic-design.md
renaming luosHAL to luos_hal
change routing table API
Change pyluos
=> Pre release 1 0 0

src/_assets/css/custom.css
- Content
- Left menu
- Search
All of them were added a +92 padding top
=> Fixed size below 800px width

src/pages/embedded/dev_env/arduino.md
Change release link and wording at step 5
=> Change release link and wording at step 5

get-started/get-started1.md
We add two different H1s in our content, prefer H2 following an existing H1.
=> Remove duplicate H1s in our content

vercel.json, versioned_docs/version-2.0.1/markdown-page.md, versioned_docs/version-2.1.0/markdown-page.md
Based on our 301 redirect dashboard, here is a fix to remove 404 pages.
=> Added some URL redirections and fixed 404 pages

sidebarsGetStarted.js, sidebarsTutorials.js, src/components/school/index/data/dataIntro.json, tutorials/bike-alarm/bike-alarm.mdx, tutorials/get-started/get-started.mdx, tutorials/get-started/get-started1.mdx, tutorials/get-started/get-started2.mdx, tutorials/get-started/get-started3.mdx, tutorials/get-started/get-started4.mdx
Just change several tutorial titles (get started part 1 et part 4) and bike alarm
=> new titles for several tutorials

vercel.json
- Add redirection from /faq/list to /faq
=> Fix missing SEO rules

vercel.json
Reported by Google Search console
\`\`\`c<br />
\`\`\`<br />
- …
=> Add some redirections

src/theme/Footer/index.js
=> fix broken logo

src/theme/TOC/index.js
=> fix missing alt

src/components/school/index/intro.js
With the docusaurus dependancies '@docusaurus/router' (and peer dep : 'react-router-dom'), we can now filter our content and share the URL to users.
=> [Feat] Add URL query parameters to enable content filtering

docs/contribute-to-luos.mdx
Update contribution page: 
- Contribution without knowing how to code
- Info on how to contribute with new HAL 
\`\`\`c<br />
// Some C language …
=> Update contribution page

src/theme/Footer/index.js, src/theme/TOC/styles.module.css
=> fix seo footer & add darkmode author box

tutorials/morse/add-service.mdx
=> form morse

blog/2022-08-30-q-and-a-august-2022-first-part.mdx, blog/2022-08-30-q-and-a-august-2022-second-part.mdx
We were waiting for Simon's review to add the internal links connecting the two articles, this PR has this objective
\`\`\`c<br />
// Some C …
=> Finalize the Q&A article to add links

tutorials/pio/pio.mdx
=> fix pio tutorial title

src/components/school/index/intro.js, src/theme/BlogListPage/index.js, tutorials/get-started/get-started3.mdx, tutorials/index.mdx, tutorials/integrations.mdx, tutorials/trainings.mdx, tutorials/usecases.mdx
Fix broken images in our Get Started tutorial and some problems with H1
\`\`\`c<br />
\`\`\`<br />
- "Luos engine" has a …
=> Fix SEO issues

src/components/Image.js, src/components/roadmap/Roadmap.js
=> fix img roadmap mobile

sidebarsTutorials.js
=> temp fix for bottom tutorials links
