Luos-io/Documentation

get-started/get-started1.md

Linux users need to modify udev-rules to be able to flash their boards with PlatformIO.
This PR is linked to this [Issue](https://github.com/Luos-io/Documentation/issues/169).

Add linux USB access in getting started

---

.github/dependabot.yml

As stated here : https://github.com/facebook/docusaurus/pull/7102#pullrequestreview-935447321, we'll not follow React 18 updates as long Docusaurus and their own dependencies are not update

Ignore React 18 dependencies

---

tutorials/freertos/intro.mdx

Fix FeeRTOS title

---

tutorials/freertos/intro.mdx

Fix Alt text

---

docusaurus.config.js

Switch docusaurus.config Url from docs.luos.io to www.luos.io

---

docs/api/api-json.mdx

There are broken links in our API JSON doc (Github links)
\`\`\`c<br />
// Some C language …

Update API JSON 404 links

---

src/components/index/header/header.js

A SDK > An SDK
\`\`\`c<br />
\`\`\`<br />
- "Luos engine" has a …

Update header.js to modify a SDK to an SDK

---

docs/compatibility/mcu_demoboard.mdx

Modify Microship to Microchip

---

docs/compatibility/mcu_demoboard.mdx

add seeeduino to list compat board

---

src/theme/Footer/index.js

fix github btn

---

sidebarsTutorials.js

fix sidebar tutorials

---

docusaurus.config.js

temp rollback trailingSlash

---

docusaurus.config.js
vercel.json

try remove param in vercel config

---

src/components/school/index/data/dataIntro.json

remove slash

---

docs/hardware-consideration/test-your-configuration.mdx
docs/luos-technology/services/profile.mdx
tutorials/arduino/intro.mdx
tutorials/your-first-detection/your-first-detection.mdx
tutorials/your-first-message/your-first-message.mdx
tutorials/your-first-service/your-first-service.mdx
versioned_docs/version-2.5.0/hardware-consideration/test-your-configuration.mdx
versioned_docs/version-2.5.0/luos-technology/services/profile.mdx

Fix 404 broken links using Semrush file #2

---

src/theme/DocVersionBadge/index.d.ts
src/theme/DocVersionBadge/index.js

add link to github in version badge

---

tutorials/get-started/get-started1.mdx
tutorials/get-started/get-started2.mdx
tutorials/get-started/get-started3.mdx
tutorials/get-started/get-started4.mdx
tutorials/your-first-detection/embedded-app.mdx
tutorials/your-first-message/send-message.mdx
tutorials/your-first-service/create-a-package.mdx

…page with a quiz
\`\`\`c<br />
\`\`\`<br />
- "Luos engine" has …

Put "test your skills" at the end and added a title number

---

faq/008.upload_arduino_bug.mdx
faq/index.mdx

Troubleshooting page for arduino upload

---

vercel.json

Add 301 redirects to avoid 404
\`\`\`c<br />
\`\`\`<br />
- …

Add some redirections

---

docs/tools/index.mdx

Modify BootLoder to Bootloader

---

faq/008.upload_arduino_bug.mdx

[FAQ] fixed typos and sentence order

---

docs/luos-technology/message/advanced-message.mdx
docs/luos-technology/message/basic-message.mdx
docs/luos-technology/message/handling-message.mdx
docs/luos-technology/message/message.mdx
docs/tools/monitoring.mdx

change serviceID and statistic

---

src/components/index/anatomy/anatomy.js

We had a 308 redirect on the **Topology and routing table link**.
\`\`\`c<br />
\`\`\`<br />
- "Luos engine" has a upper …

Modify a link to avoid a 308 redirect

---

src/components/typeform/index.js

The "lazy" parameter allow us to defer loading of the typeform quizz when we scroll down to the page only. This solve our problem and enhance the performance of the page.
- Long codes are put into blocks of code with three grave accent on each side, and …

Enable lazyloading to avoid auto-scroll on the page

---

docs/integrations/index.mdx
docs/tools/index.mdx
sidebarsDocs.js
versioned_docs/version-2.6.0/integrations/index.mdx
versioned_docs/version-2.6.0/tools/index.mdx
versioned_sidebars/version-2.6.0-sidebars.json

Modify our 'Coming soon' description in Built-in tools and Integrations. We also add an error in the PlatformIO link.
\`\`\`c<br />
// Some C …

Modify coming soon description

---

docs/tools/bootloader.mdx

[Bootloader] Explain Multicast use

---

tutorials/get-started/get-started.mdx

*This PR is linked to #536 *
*Added the instructions to run the built file on Linux based OS. Getting-Started Docs only mentioned the instructions for windows based OS previously.*
- [ ✅ ] From a technical point of view.
- [ ✅ ] From a grammatical point of view (spelling mistakes, typos, clarity, etc.), and following the guidelines at the bottom.
- [ ❌ ] You requested a technical review.
- [ ❌ ] You requested a grammatical review.
- [ ❌ ] You validated with @K0rdan or @alexgeron-Luos that it is safe to merge.
- Colons (:), semi-colons (;), exclamation (!), and interrogation points (?) are not …

Updated the getting started docs for linux based OS.
